---
- name: Update web, nfs, and db servers
  hosts: webservers, nfs,
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version on RedHat/CentOS
      yum:
        name: wireshark
        state: latest
      when: ansible_facts['os_family'] == 'RedHat'

    - name: ensure wireshark is at the latest version on Debian/Ubuntu
      apt:
        name: wireshark
        state: latest
      when: ansible_facts['os_family'] == 'Debian'

    - name: create a directory
      file:
        path: /folder
        state: directory
        mode: "0755"

    - name: create a file
      copy:
        content: "adding a file content" 
        dest: /folder/ansible.txt
        mode: '0644'

    - name: set time zone to UTC
      timezone:
        name: UTC

    - name: run a shell script
      shell: |
        #!/bin/bash
        echo "run and test this shell script"
      args:
        creates: /folder/my_script.txt

- name: Update LB and db server
  hosts: lb, db
  become: yes
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes
      when: ansible_facts['os_family1'] == 'Debian'

    - name: ensure wireshark is at the latest version on Ubuntu
      apt:
        name: wireshark
        state: latest
      when: ansible_facts['os_family'] == 'Debian'

    - name: create a directory
      file:
        path: /folder
        state: directory
        mode: "0755"

    - name: create a file
      copy:
        content: "adding a file content" 
        dest: /folder/ansible.txt
        mode: '0644'

    - name: set time zone to UTC
      timezone:
        name: UTC

    - name: run a shell script
      shell: |
        #!/bin/bash
        echo "run and test this shell script"
        echo "Executed on $(date)" >> /folder/my_script.txt
      args:
        creates: /folder/my_script.txt
