[tooling]
172.31.87.80 ansible_ssh_user=ec2-user


[nginx]
172.31.175.129 ansible_ssh_user=ubuntu

[db:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python

[db]
172.31.23.137 ansible_ssh_user=ubuntu

[todo]
172.31.154.241 ansible_ssh_user=ec2-user