---
- name: Install Apache
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Install Git
  ansible.builtin.yum:
    name: git
    state: present

- name: Install EPEL release
  ansible.builtin.command:
    cmd: sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y

- name: Install dnf-utils and Remi repository
  ansible.builtin.command:
    cmd: sudo dnf install dnf-utils http://rpms.remirepo.net/enterprise/remi-release-9.rpm -y

- name: Reset PHP module
  ansible.builtin.command:
    cmd: sudo module reset php -y

- name: Install PHP and extensions
  ansible.builtin.yum:
    name:
      - php
      - php-opcache
      - php-gd
      - php-curl
      - php-mysqlnd
    state: present

- name: Install MySQL Client
  ansible.builtin.yum:
    name: mysql
    state: present

- name: Start PHP-FPM Service
  ansible.builtin.service:
    name: php-fpm
    state: started

- name: Enable PHP-FPM Service
  ansible.builtin.systemd:
    name: php-fpm
    enabled: true

- name: Set SELinux boolean for httpd_execmem
  ansible.builtin.command:
    cmd: sudo setsebool -p httpd_execmem 1

- name: Clone a repository
  ansible.builtin.git:
    repo: https://github.com/GodwinGNS/tooling.git
    dest: /var/www/html
    force: yes

- name: Copy HTML content to one level up
  ansible.builtin.command:
    cmd: cp -r /var/www/html/html/ /var/www/

- name: Start Apache service if not started
  ansible.builtin.service:
    name: httpd
    state: started

- name: Recursively remove /var/www/html/html/ directory
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent

