---
- name: Include dynamic variables
  include_vars: ../dynamic-assignment/env-vars.yml
  tags:
    - always

- hosts: webservers
  name: Webserver assignment
  tasks:
    - import_playbook: ../static-assignments/uat-webservers.yml

- import_playbook: ../static-assignments/db-servers.yml

- import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required

  #########################

- hosts: db
- name: database assignment
  import_playbook: ../static-assignments/database.yml

- hosts: nginx
- name: nginx assignment
  import_playbook: ../static-assignments/nginx.yml

- hosts: todo
- name: Deploy the todo application
  import_playbook: ../static-assignments/deployment.yml
# - hosts: artifactory
# - name: artifactory assignment
#   import_playbook: ../static-assignments/artifactory.yml
